local M = {}

M.generic = {
    ["q"] = { function() require("vaultview").hide() end, mode = "n", noremap = true, nowait = true, },
    ["<S-h>"] = { function() require("vaultview").goto_previous_page() end, mode = "n", noremap = true, nowait = true, },
    ["<S-l>"] = { function() require("vaultview").goto_next_page() end, mode = "n", noremap = true, nowait = true, },
    ["p"] = { function() require("vaultview").goto_previous_board() end, mode = "n", noremap = true, nowait = true, },
    ["n"] = { function() require("vaultview").goto_next_board() end, mode = "n", noremap = true, nowait = true, },
    ["1"] = { function() require("vaultview").goto_board(1) end, mode = "n", noremap = true, nowait = true, },
    ["2"] = { function() require("vaultview").goto_board(2) end, mode = "n", noremap = true, nowait = true, },
    ["3"] = { function() require("vaultview").goto_board(3) end, mode = "n", noremap = true, nowait = true, },
    ["4"] = { function() require("vaultview").goto_board(4) end, mode = "n", noremap = true, nowait = true, },
    ["5"] = { function() require("vaultview").goto_board(5) end, mode = "n", noremap = true, nowait = true, },
    ["6"] = { function() require("vaultview").goto_board(6) end, mode = "n", noremap = true, nowait = true, },
    ["7"] = { function() require("vaultview").goto_board(7) end, mode = "n", noremap = true, nowait = true, },
    ["8"] = { function() require("vaultview").goto_board(8) end, mode = "n", noremap = true, nowait = true, },
    ["9"] = { function() require("vaultview").goto_board(9) end, mode = "n", noremap = true, nowait = true, },
    ["r"] = { function() require("vaultview").refresh_focused_entry_content() end, mode = "n", noremap = true, nowait = true, },
    ["R"] = { function() require("vaultview").fast_refresh() end, mode = "n", noremap = true, nowait = true, },
    -- ["<C-f>"] = { function() require("vaultview._commands.open.runner").run_pick_list() end, mode = "n", noremap = true, nowait = true, },
    -- ["f"] = { function() require("vaultview._commands.open.runner").run_pick_card() end, mode = "n", noremap = true, nowait = true, },
    -- ["F"] = { function() require("vaultview._commands.open.runner").run_pick_content() end, mode = "n", noremap = true, nowait = true, },
    ["?"] = { function() require("vaultview").open_help() end, mode = "n", noremap = true, nowait = true, },
    ["<M-h>"] = { function() require("vaultview").focus_first_list() end, mode = "n", noremap = true, nowait = true, },
    ["h"] = { function() require("vaultview").focus_previous_list() end, mode = "n", noremap = true, nowait = true, },
    ["c"] = { function() require("vaultview").focus_center_list() end, mode = "n", noremap = true, nowait = true, },
    ["l"] = { function() require("vaultview").focus_next_list() end, mode = "n", noremap = true, nowait = true, },
    ["<M-l>"] = { function() require("vaultview").focus_last_list() end, mode = "n", noremap = true, nowait = true, },
    ["gg"] = { function() require("vaultview").focus_first_entry() end, mode = "n", noremap = true, nowait = true, },
    ["k"] = { function() require("vaultview").focus_previous_entry() end, mode = "n", noremap = true, nowait = true, },
    ["j"] = { function() require("vaultview").focus_next_entry() end, mode = "n", noremap = true, nowait = true, },
    ["G"] = { function() require("vaultview").focus_last_entry() end, mode = "n", noremap = true, nowait = true, },
    ["<A-k>"] = { function() require("vaultview").focus_previous_entry_page() end, mode = "n", noremap = true, nowait = true, },
    ["<A-j>"] = { function() require("vaultview").focus_next_entry_page() end, mode = "n", noremap = true, nowait = true, },
    ["<CR>"] = { function() require("vaultview").open_in_neovim() end, mode = "n", noremap = true, nowait = true, },
    ["o"] = { function() require("vaultview").open_in_obsidian() end, mode = "n", noremap = true, nowait = true, },
}


return M
