
local A = require("vaultview.actions")

local function map(lhs, action)
    vim.keymap.set("n", lhs, A[action], { buffer = true, silent = true, noremap = true })
end

-- defaults
map("q", "Hide")
map("<S-h>", "PreviousPage")
map("<S-l>", "NextPage")
map("p", "PreviousBoard")
map("n", "NextBoard")
map("1", "Board1")
map("2", "Board2")
map("3", "Board3")
map("4", "Board4")
map("5", "Board5")
map("6", "Board6")
map("7", "Board7")
map("8", "Board8")
map("9", "Board9")
map("?", "Help")
map("r", "RefreshEntry")
map("R", "FastRefresh")
-- map("<C-f>", "PickList")
-- map("f", "PickEntry")
-- map("F", "PickContent")
map("<M-h>", "FirstList")
map("h", "PreviousList")
map("c", "CenterList")
map("l", "NextList")
map("<M-l>", "LastList")
map("gg", "FirstEntry")
map("k", "PreviousEntry")
map("j", "NextEntry")
map("G", "LastEntry")
map("<A-k>", "PreviousPageInList")
map("<A-j>", "NextPageInList")
map("o", "OpenInNeovim")
map("<CR>", "OpenInObsidian")
